/*
* generated by Xtext
*/
package com.proxiad.emfcustomizer.stylesheet.dsl.outline;

import org.eclipse.xtext.ui.common.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class StylesheetTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
