/*
 * generated by Xtext
 */
package com.proxiad.emfcustomizer.stylesheet.dsl.formatting;

import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;

/**
 * This class contains custom formatting description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#formatting
 * on how and when to use it 
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an example
 */
public class StylesheetFormatter extends AbstractDeclarativeFormatter {
	
	@Override
	protected void configureFormatting(FormattingConfig c) {
		com.proxiad.emfcustomizer.stylesheet.dsl.services.StylesheetGrammarAccess f = (com.proxiad.emfcustomizer.stylesheet.dsl.services.StylesheetGrammarAccess) getGrammarAccess();

		//...
	}
}
