grammar com.proxiad.emfcustomizer.stylesheet.dsl.Stylesheet with org.eclipse.xtext.common.Terminals

generate stylesheet "http://www.proxiad.com/emfcustomizer/stylesheet/dsl/Stylesheet"

Model :
	(imports+=Import)*
	(elements+=Type)*;
	
Import :
	'import' importURI=STRING;
	
Type:
	SimpleType | Entity;
	
SimpleType:
	'type' name=ID;
	
Entity :
	'entity' name=ID ('extends' extends=[Entity])? '{'
		properties+=Property*
	'}';

Property:
	'property' name=ID ':' type=[Type] (many?='[]')?;
	
