/*
 * generated by Xtext
 */
package com.proxiad.emfcustomizer.stylesheet.dsl;

/**
 * Use this class to register components to be used within the IDE.
 */
public class StylesheetRuntimeModule extends com.proxiad.emfcustomizer.stylesheet.dsl.AbstractStylesheetRuntimeModule {

}
