/*
* generated by Xtext
*/
package com.proxiad.emfcustomizer.stylesheet.dsl.contentassist;

import com.proxiad.emfcustomizer.stylesheet.dsl.contentassist.AbstractStylesheetProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class StylesheetProposalProvider extends AbstractStylesheetProposalProvider {

}
